// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drdg.proto

package com.drdg.emp;

public final class DrdgProbuf {
  private DrdgProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmpOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string empName = 1;
    /**
     * <code>required string empName = 1;</code>
     */
    boolean hasEmpName();
    /**
     * <code>required string empName = 1;</code>
     */
    java.lang.String getEmpName();
    /**
     * <code>required string empName = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmpNameBytes();

    // required string empQQ = 2;
    /**
     * <code>required string empQQ = 2;</code>
     */
    boolean hasEmpQQ();
    /**
     * <code>required string empQQ = 2;</code>
     */
    java.lang.String getEmpQQ();
    /**
     * <code>required string empQQ = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmpQQBytes();

    // required string empWeb = 3;
    /**
     * <code>required string empWeb = 3;</code>
     */
    boolean hasEmpWeb();
    /**
     * <code>required string empWeb = 3;</code>
     */
    java.lang.String getEmpWeb();
    /**
     * <code>required string empWeb = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmpWebBytes();
  }
  /**
   * Protobuf type {@code Emp}
   */
  public static final class Emp extends
      com.google.protobuf.GeneratedMessage
      implements EmpOrBuilder {
    // Use Emp.newBuilder() to construct.
    private Emp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Emp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Emp defaultInstance;
    public static Emp getDefaultInstance() {
      return defaultInstance;
    }

    public Emp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Emp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              empName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              empQQ_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              empWeb_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drdg.emp.DrdgProbuf.internal_static_Emp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drdg.emp.DrdgProbuf.internal_static_Emp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drdg.emp.DrdgProbuf.Emp.class, com.drdg.emp.DrdgProbuf.Emp.Builder.class);
    }

    public static com.google.protobuf.Parser<Emp> PARSER =
        new com.google.protobuf.AbstractParser<Emp>() {
      public Emp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Emp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Emp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string empName = 1;
    public static final int EMPNAME_FIELD_NUMBER = 1;
    private java.lang.Object empName_;
    /**
     * <code>required string empName = 1;</code>
     */
    public boolean hasEmpName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string empName = 1;</code>
     */
    public java.lang.String getEmpName() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          empName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string empName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmpNameBytes() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string empQQ = 2;
    public static final int EMPQQ_FIELD_NUMBER = 2;
    private java.lang.Object empQQ_;
    /**
     * <code>required string empQQ = 2;</code>
     */
    public boolean hasEmpQQ() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string empQQ = 2;</code>
     */
    public java.lang.String getEmpQQ() {
      java.lang.Object ref = empQQ_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          empQQ_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string empQQ = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmpQQBytes() {
      java.lang.Object ref = empQQ_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empQQ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string empWeb = 3;
    public static final int EMPWEB_FIELD_NUMBER = 3;
    private java.lang.Object empWeb_;
    /**
     * <code>required string empWeb = 3;</code>
     */
    public boolean hasEmpWeb() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string empWeb = 3;</code>
     */
    public java.lang.String getEmpWeb() {
      java.lang.Object ref = empWeb_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          empWeb_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string empWeb = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmpWebBytes() {
      java.lang.Object ref = empWeb_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empWeb_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      empName_ = "";
      empQQ_ = "";
      empWeb_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEmpName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmpQQ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmpWeb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmpNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmpQQBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmpWebBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmpNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmpQQBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmpWebBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.drdg.emp.DrdgProbuf.Emp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.drdg.emp.DrdgProbuf.Emp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Emp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.drdg.emp.DrdgProbuf.EmpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.drdg.emp.DrdgProbuf.internal_static_Emp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.drdg.emp.DrdgProbuf.internal_static_Emp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.drdg.emp.DrdgProbuf.Emp.class, com.drdg.emp.DrdgProbuf.Emp.Builder.class);
      }

      // Construct using com.drdg.emp.DrdgProbuf.Emp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        empName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        empQQ_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        empWeb_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.drdg.emp.DrdgProbuf.internal_static_Emp_descriptor;
      }

      public com.drdg.emp.DrdgProbuf.Emp getDefaultInstanceForType() {
        return com.drdg.emp.DrdgProbuf.Emp.getDefaultInstance();
      }

      public com.drdg.emp.DrdgProbuf.Emp build() {
        com.drdg.emp.DrdgProbuf.Emp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.drdg.emp.DrdgProbuf.Emp buildPartial() {
        com.drdg.emp.DrdgProbuf.Emp result = new com.drdg.emp.DrdgProbuf.Emp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.empName_ = empName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.empQQ_ = empQQ_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.empWeb_ = empWeb_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.drdg.emp.DrdgProbuf.Emp) {
          return mergeFrom((com.drdg.emp.DrdgProbuf.Emp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.drdg.emp.DrdgProbuf.Emp other) {
        if (other == com.drdg.emp.DrdgProbuf.Emp.getDefaultInstance()) return this;
        if (other.hasEmpName()) {
          bitField0_ |= 0x00000001;
          empName_ = other.empName_;
          onChanged();
        }
        if (other.hasEmpQQ()) {
          bitField0_ |= 0x00000002;
          empQQ_ = other.empQQ_;
          onChanged();
        }
        if (other.hasEmpWeb()) {
          bitField0_ |= 0x00000004;
          empWeb_ = other.empWeb_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmpName()) {
          
          return false;
        }
        if (!hasEmpQQ()) {
          
          return false;
        }
        if (!hasEmpWeb()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.drdg.emp.DrdgProbuf.Emp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.drdg.emp.DrdgProbuf.Emp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string empName = 1;
      private java.lang.Object empName_ = "";
      /**
       * <code>required string empName = 1;</code>
       */
      public boolean hasEmpName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string empName = 1;</code>
       */
      public java.lang.String getEmpName() {
        java.lang.Object ref = empName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          empName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string empName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmpNameBytes() {
        java.lang.Object ref = empName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string empName = 1;</code>
       */
      public Builder setEmpName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        empName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string empName = 1;</code>
       */
      public Builder clearEmpName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        empName_ = getDefaultInstance().getEmpName();
        onChanged();
        return this;
      }
      /**
       * <code>required string empName = 1;</code>
       */
      public Builder setEmpNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        empName_ = value;
        onChanged();
        return this;
      }

      // required string empQQ = 2;
      private java.lang.Object empQQ_ = "";
      /**
       * <code>required string empQQ = 2;</code>
       */
      public boolean hasEmpQQ() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string empQQ = 2;</code>
       */
      public java.lang.String getEmpQQ() {
        java.lang.Object ref = empQQ_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          empQQ_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string empQQ = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmpQQBytes() {
        java.lang.Object ref = empQQ_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empQQ_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string empQQ = 2;</code>
       */
      public Builder setEmpQQ(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        empQQ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string empQQ = 2;</code>
       */
      public Builder clearEmpQQ() {
        bitField0_ = (bitField0_ & ~0x00000002);
        empQQ_ = getDefaultInstance().getEmpQQ();
        onChanged();
        return this;
      }
      /**
       * <code>required string empQQ = 2;</code>
       */
      public Builder setEmpQQBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        empQQ_ = value;
        onChanged();
        return this;
      }

      // required string empWeb = 3;
      private java.lang.Object empWeb_ = "";
      /**
       * <code>required string empWeb = 3;</code>
       */
      public boolean hasEmpWeb() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string empWeb = 3;</code>
       */
      public java.lang.String getEmpWeb() {
        java.lang.Object ref = empWeb_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          empWeb_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string empWeb = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmpWebBytes() {
        java.lang.Object ref = empWeb_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empWeb_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string empWeb = 3;</code>
       */
      public Builder setEmpWeb(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        empWeb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string empWeb = 3;</code>
       */
      public Builder clearEmpWeb() {
        bitField0_ = (bitField0_ & ~0x00000004);
        empWeb_ = getDefaultInstance().getEmpWeb();
        onChanged();
        return this;
      }
      /**
       * <code>required string empWeb = 3;</code>
       */
      public Builder setEmpWebBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        empWeb_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Emp)
    }

    static {
      defaultInstance = new Emp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Emp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Emp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Emp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndrdg.proto\"5\n\003Emp\022\017\n\007empName\030\001 \002(\t\022\r\n\005" +
      "empQQ\030\002 \002(\t\022\016\n\006empWeb\030\003 \002(\tB\032\n\014com.drdg." +
      "empB\nDrdgProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Emp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Emp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Emp_descriptor,
              new java.lang.String[] { "EmpName", "EmpQQ", "EmpWeb", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
